-- PallyPilot HubSync: publish the PallyPilot ratings INTO EbonholdHub as a
-- build, via EBH's own public API (Create/Delete/SetActive) — data only,
-- no EBH code copied. Once active, EBH's Auto-Pick executes our catalog:
-- one brain (PallyPilot ratings), their engine (banish/reroll/freeze).
local PP = PallyPilot
local HS = PP.HubSync

local TITLE = "PallyPilot Solo Ret (synced)"

-- The server displays echo names with curly apostrophes; BuildData uses
-- straight ones. Emit both spellings so exact-match lookups always hit.
local function BothQuotes(t, name, tier)
  t[name] = tier
  local curly = string.gsub(name, "'", "\226\128\153")
  if curly ~= name then t[curly] = tier end
end

-- Curated lists win over the catalog; locked cores are S; disables are F.
local function AssembleTiers()
  local B = PP.Build
  local tiers = {}
  for n, t in pairs(B.catalog or {}) do BothQuotes(tiers, n, t) end
  for tier, list in pairs(B.tiers) do
    for _, n in ipairs(list) do BothQuotes(tiers, n, tier) end
  end
  for _, n in ipairs(B.locked) do BothQuotes(tiers, n, "S") end
  for _, n in ipairs(B.disable) do BothQuotes(tiers, n, "F") end
  return tiers
end

-- STRATEGY (field lessons 2026-08-25): Adaptive Power pays +1% damage per
-- UNIQUE active echo, so BREADTH is itself a damage multiplier — 71 uniques
-- beat 34 uniques with deeper ranks (measured: keepsy). Two modes:
--   breadth (default): everything capped at 1 copy -> Auto-Pick always
--     prefers a NEW echo over any repeat. Correct until active slots fill.
--   depth: S/core uncapped, A to 5 -> repeats rank up the core. Correct
--     only once you're at the active-echo cap (~72) or the pool is dry.
local function AssembleMaxPicks(tiers, mode)
  local mp = {}
  if mode == "depth" then
    for name, tier in pairs(tiers) do
      if tier == "S" then
        mp[name] = 0
      elseif tier == "A" then
        mp[name] = 5
      end
    end
  end
  -- breadth: empty table -> EBH's default cap of 1 for everything.
  return mp
end

function HS.Push(mode)
  mode = (mode == "depth") and "depth" or "breadth"
  local EB = EbonholdHub and EbonholdHub.Build
  if not (EB and EB.Create and EB.SetActive and EbonholdHubDB) then
    PP.print("EbonholdHub not loaded — can't sync a build into it.")
    return
  end
  local slots = (EB.GetLockedSlotCount and EB.GetLockedSlotCount())
    or PP.EchoAudit.LockSlots()
  local locked = PP.EchoAudit.BestOwned and PP.EchoAudit.BestOwned(slots) or {}

  -- Replace any previous synced build (stats reset — they're just counters).
  for id, b in pairs(EbonholdHubDB.builds or {}) do
    if b.title == TITLE and EB.Delete then pcall(EB.Delete, id) end
  end

  local tiers = AssembleTiers()
  local ok, build = pcall(EB.Create, {
    title = TITLE,
    class = "PALADIN",
    spec = 3,
    comments = "Auto-generated by PallyPilot (tooltip-verified catalog), "
      .. "mode: " .. mode .. ". breadth = uniques first (Adaptive Power), "
      .. "depth = rank the core. /pp hubsync breadth|depth to switch.",
    lockedEchoes = locked,
    echoTiers = tiers,
    echoMaxPicks = AssembleMaxPicks(tiers, mode),
    automationEnabled = true,
    author = "PallyPilot",
  })
  if not ok or not build then
    PP.print("Sync failed inside EbonholdHub.Build.Create: " .. tostring(build))
    return
  end
  local okA, err = pcall(EB.SetActive, build.id)
  if not okA then
    PP.print("Build created but SetActive failed: " .. tostring(err)
      .. " — select '" .. TITLE .. "' manually in EbonholdHub.")
    return
  end
  PP.print("Synced and ACTIVE: '" .. TITLE .. "' in " .. string.upper(mode)
    .. " mode (" .. slots .. " lock slots).")
  if #locked > 0 then
    PP.print("Suggested locks: " .. table.concat(locked, ", "))
  end
end
