-- PallyPilot HubSync: publish the PallyPilot ratings INTO EbonholdHub as a
-- build, via EBH's own public API (Create/Delete/SetActive) — data only,
-- no EBH code copied. Once active, EBH's Auto-Pick executes our catalog:
-- one brain (PallyPilot ratings), their engine (banish/reroll/freeze).
local PP = PallyPilot
local HS = PP.HubSync

local TITLE = "PallyPilot Solo Ret (synced)"

-- The server displays echo names with curly apostrophes; BuildData uses
-- straight ones. Emit both spellings so exact-match lookups always hit.
local function BothQuotes(t, name, tier)
  t[name] = tier
  local curly = string.gsub(name, "'", "\226\128\153")
  if curly ~= name then t[curly] = tier end
end

-- Curated lists win over the catalog; locked cores are S; disables are F.
local function AssembleTiers()
  local B = PP.Build
  local tiers = {}
  for n, t in pairs(B.catalog or {}) do BothQuotes(tiers, n, t) end
  for tier, list in pairs(B.tiers) do
    for _, n in ipairs(list) do BothQuotes(tiers, n, tier) end
  end
  for _, n in ipairs(B.locked) do BothQuotes(tiers, n, "S") end
  for _, n in ipairs(B.disable) do BothQuotes(tiers, n, "F") end
  return tiers
end

-- CRITICAL (field lesson 2026-08-25): EBH's GetMaxPicks defaults to 1 for
-- names missing from echoMaxPicks — an empty table means Auto-Pick NEVER
-- stacks ranks, producing a rank-1-everything run that dies on trash.
-- Rank depth is the power curve: S/core stack without cap (0 = unlimited),
-- A stacks to 5, B stays at 1 copy (breadth feeds Adaptive Power).
local function AssembleMaxPicks(tiers)
  local mp = {}
  for name, tier in pairs(tiers) do
    if tier == "S" then
      mp[name] = 0
    elseif tier == "A" then
      mp[name] = 5
    end
  end
  return mp
end

function HS.Push()
  local EB = EbonholdHub and EbonholdHub.Build
  if not (EB and EB.Create and EB.SetActive and EbonholdHubDB) then
    PP.print("EbonholdHub not loaded — can't sync a build into it.")
    return
  end
  local slots = (EB.GetLockedSlotCount and EB.GetLockedSlotCount())
    or PP.EchoAudit.LockSlots()
  local locked = PP.EchoAudit.BestOwned and PP.EchoAudit.BestOwned(slots) or {}

  -- Replace any previous synced build (stats reset — they're just counters).
  for id, b in pairs(EbonholdHubDB.builds or {}) do
    if b.title == TITLE and EB.Delete then pcall(EB.Delete, id) end
  end

  local tiers = AssembleTiers()
  local ok, build = pcall(EB.Create, {
    title = TITLE,
    class = "PALADIN",
    spec = 3,
    comments = "Auto-generated by PallyPilot from the tooltip-verified echo "
      .. "catalog. S/core stack uncapped, A to 5, B single-copy. "
      .. "Re-run /pp hubsync after rating changes.",
    lockedEchoes = locked,
    echoTiers = tiers,
    echoMaxPicks = AssembleMaxPicks(tiers),
    automationEnabled = true,
    author = "PallyPilot",
  })
  if not ok or not build then
    PP.print("Sync failed inside EbonholdHub.Build.Create: " .. tostring(build))
    return
  end
  local okA, err = pcall(EB.SetActive, build.id)
  if not okA then
    PP.print("Build created but SetActive failed: " .. tostring(err)
      .. " — select '" .. TITLE .. "' manually in EbonholdHub.")
    return
  end
  PP.print("Synced and ACTIVE: EbonholdHub build '" .. TITLE .. "' ("
    .. slots .. " lock slots). Auto-Pick now follows the PallyPilot ratings.")
  if #locked > 0 then
    PP.print("Suggested locks: " .. table.concat(locked, ", "))
  end
end
